name: e2e-trigger poc
on:
  issue_comment:
    types: [created]
jobs:
  job1:
    if: contains(github.event.comment.html_url, '/pull/')
    runs-on: [ubuntu-latest]
    steps:
      - name: Start e2e test
        if: contains(github.event.comment.body, '/e2e')
        run: echo running e2e-test 2